# With --minconfig , you can easily used this configurations as reference.
# It's useful to users who are new to KubeEdge, and you can modify/create your own configs accordingly.
# This configuration is suitable for beginners.

apiVersion: edgecore.config.kubeedge.io/v1alpha1
database:
    dataSource: /var/lib/kubeedge/edgecore.db
kind: EdgeCore
modules:
    edgeHub:
        heartbeat: 15
        httpServer: https://MASTER_NODE:10002
        tlsCaFile: /etc/kubeedge/ca/rootCA.crt
        tlsCertFile: /etc/kubeedge/certs/server.crt
        tlsPrivateKeyFile: /etc/kubeedge/certs/server.key
        token: TOKEN
        websocket:
            enable: true
            handshakeTimeout: 30
            readDeadline: 15
            server: MASTER_NODE:10000
            writeDeadline: 15
    edged:
        cgroupDriver: cgroupfs
        cgroupRoot: ""
        cgroupsPerQOS: true
        clusterDNS: ""
        clusterDomain: ""
        devicePluginEnabled: false
        dockerAddress: unix:///var/run/docker.sock
        gpuPluginEnabled: false
        hostnameOverride: EDGE_NODE
        interfaceName: eth0
        nodeIP: EDGE_NODE
        podSandboxImage: kubeedge/pause:3.1
        remoteImageEndpoint: unix:///var/run/dockershim.sock
        remoteRuntimeEndpoint: unix:///var/run/dockershim.sock
        runtimeType: docker
    eventBus:
        mqttMode: 0
        mqttQOS: 0
        mqttRetain: false
        mqttServerExternal: tcp://127.0.0.1:1883
        mqttServerInternal: tcp://127.0.0.1:1884